language: python
python:
  - "3.6"
    
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
    - py.test --cov-report term-missing --cov=test
    - py.test --doctest-modules --cov=test --cov-report term-missing
after_success:
    - coveralls
    
notifications:
  email:
    recipients:
      - valentk777@gmail.com
    on_success: always
    on_failure: always
